### ISSUE TITLE
[epic] Read Service with CKAN v2 compatibility

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-api#1]
We are using Hasura as the base wrapper around Postgres.

We need a backwards compatible API

```bash
# dapi-endpoint includes version e.g. data-api.ckan.com/v1/ ...
{dapi-endpoint}/{dapi-id}/graphql  # raw Hasura
{dapi-endpoint}/{dapi-id}/datastore_search  # CKAN DataStore /api/3/datastore_search

# let's see about this one (if hard we may skip for now)
{dapi-endpoint}/{dapi-id}/datastore_search_sql/  # CKAN DS SQL /api/3/datastore_search_sql
```

## Terminology

* dapi-id = table name in postgres (?) tbc
  * NB: hasura does not allow - in table names ...

## Acceptance

* [x] We have a new graphql endpoint
  * [x] You can get CSV and xlsx data from it (?)
* [ ] We have backwards compatible `datastore_search`
* [ ] We have backwards compatible `datastore_search_sql`
* [x] We support CORS
* [ ] We have a hook for metrics (to google analytics)

BONUS

* [ ] We implement existing permissions (what are they?)

## Tasks

* [x] Setup - create / define repo
  * [x] Bootstrap an Express app (?use a boilerplate instead of doing it from scratch https://expressjs.com/en/starter/generator.html)
  * [x] Setup tests - what should we use here? Supertest remains the default for node http server tests ...
  * [x] Setup mocks / fixtures ie. the fixture postgres database
    * [ ] For mocks we can either use nock or mitm.js (interesting to give a try)
  * [x] Setup CI to run the tests
* [x] Deploy to Hasura-dev on our cluster
* [x] Create the graphql endpoint
  * [x] should serve as a proxy from/to hasura graphql server
  * [x] receives a reqeust => preps a graphql query => hits hasura => pipes back the response
* [x] Create `datastore_search` endpoint
* [ ] Create `datastore_search_sql` endpoint

## Analysis

```mermaid
graph TD

subgraph Read API service
  hasura[Hasura]
  apiwrapper[NodeJS wrapper app]
end

postgres[Postgres]

apiwrapper --> hasura
hasura --> postgres
```

**Comment by leomrocha** [comment]
@rufuspollock @EvgeniiaVak 

While this design might be good for this particular case, I would propose a more general idea on how to deal with multiple different data warehouse backends, exposing hasura directly is an option.

After some thought on the needs and variability that the Next API will have depending on customers and even for a single customer on the different reporting capabilities (example, full data download/upload). This is just an initial idea to start a deeper discussion, please let me know if I should move this to another thread or place.

In reference to [design of data api](https://github.com/datopian/data-api/issues/1) I would propose to extend a bit the idea with something like this:

```mermaid
graph TD

Client --> A[API Next]
A -->|Service Call| B(Plugin Dispatcher)

subgraph Plugin System

    B --> C{Plugin Selection}
    C -->|1| HA[hasura]
    C -->|2| PG[Postgres]
    C -->|3| SFTP
    C --> DOTS[...]
    C -->|N| GQL[GraphQL]

end
```

The difference being that instead of the call and return passing directly to the through end system it passes through a plugin system, this way there are a few things that can be added painlessly (kind of). 
Some of the advantages that I see for this approach would be:
- for queries that return big results (GB order?) the result returned can be an URL pointing to a saved result in a file on a file server (for example SFTP server), this adds some resilience if the transfer fails (the client can start the transfer again, a result file hash can be computed and returned for ), it also can be used for intermediate results that can be used later for different output queries.
- new backends can be added without the need to touch the main source package

What a plugin would do:
- register itself and it's basic exposed api
- provide it's documentation
- act as a bridge between the API and a data backend
- could query multiple backends/databases if needed

**Comment by leomrocha** [comment]
I don't know how this is currently handled but an example of a plugin that handles custom heavy queries that might take some time could be:
The plugin takes the call, puts the new job in a queue with a jobID
the API returns:
- a jobID to be able to poll to see if the result is available, there is an error or still waiting to start
Once the job is available querying for the job ID can return an URL where the result is available and for how long it will be available before deletion

The polling ID is simple enough for many applications, while the system could be later updated to handle pub/sub (but for this the calling system needs to be able to also handle its subscriptions)

**Comment by rufuspollock** [comment]
@EvgeniiaVak @leomrocha can you update on where we are with this?

**Comment by leomrocha** [comment]
@rufuspollock At the moment we have a basic API (as explained in the README file) that is not backwards compatible. It can take graphql queries and queries with other parametrizations.

We could make a few changes to have backwards compatibility adding endpoints that behind the scenes convert the calls to JSON, or doing a conversion in the same endpoints but I would suggest we keep the new API and deprecate the CKAN one adding specific compatibility endpoints giving some deadline (a few years?) to move to the new ones.

The `datastore_search_sql` endpoint should be deprecated a directly exposing the DB has many problems for portability and maintenance. 

Not all the endpoints make sense with the new syntax as some can be merged.

In the case of making a GraphQL query, the server redirects to graphql

Downloads for CSV and XLSX should be added but I wouldn't do that as a graphql response (endpoint), instead what I would do is to maintain the graphql query and as response do a file stream directly, or saving to a file server with some file retention policy and returning the file url as a redirect and download.

**Comment by leomrocha** [comment]
@rufuspollock @anuveyatsu @EvgeniiaVak I would like your thoughts here.

This issue might be already outdated and some discussion is needed on the CKAN backwards compatibility.

I would like to avoid exposing the `datastore_search_sql` endpoint as it not only makes another security risk headache but I  think we should deprecate it. Maybe on the services that are still using this endpoint keep using CKAN while the systems are migrated to the new GraphQL and `datastore_search` endpoints.

For the complete backwards compatibility of `datastore_search` with CKAN there are still some things to implement that with the changes make no real sense or are not easily feasible. If is needed for some current migration we can implement the needed features, but I would make it as per need basis only and not as a general requirement. The same if a migration can be done with the `datastore_search_sql` endpoint, I would not include it in the data-api distribution but only do it in the cases that need it for migrating from CKAN and with the view of taking it out in the future.

I think one of the most important features to do right now is to implement access rights and security.

**Comment by rufuspollock** [comment]
> I would like to avoid exposing the datastore_search_sql endpoint as it not only makes another security risk headache but I think we should deprecate it. Maybe on the services that are still using this endpoint keep using CKAN while the systems are migrated to the new GraphQL and datastore_search endpoints.

I hear you .... and some people do use this so we will need it. I think for this we could implement a function purely in nodejs wrapper (outside Hasura). It's a relatively straightforward to do i think.

> For the complete backwards compatibility of datastore_search with CKAN there are still some things to implement that with the changes make no real sense or are not easily feasible. If is needed for some current migration we can implement the needed features, but I would make it as per need basis only and not as a general requirement. The same if a migration can be done with the datastore_search_sql endpoint, I would not include it in the data-api distribution but only do it in the cases that need it for migrating from CKAN and with the view of taking it out in the future.

Can we make sure what is and is not implemented is very clearly documented in the README - is that something we could do right now.

> I think one of the most important features to do right now is to implement access rights and security.

Can you open a separate issue about this if we don't have it already. For this i'm anticipating that we move to the JWT approach using ckanext-authz i.e. ckan using ckanext-authz gives out tokens that this data api service can then use to authorize requests.
