### ISSUE TITLE
Basic API optional parameters from CKAN datastore API

### ISSUE THREAD

**Issue by leomrocha** [datopian/data-api#11]
This is a follow up of [issue #7 ](https://github.com/datopian/data-api/issues/7)

# Acceptance

* [x] The data-api app provides the parameters 
* [x] The data-api app provides response streaming 

# Tasks

Implement the following parameters

* [x] offset 
* [x] sort 
* [ ] ~~include total(bool) total matching record count (int) default:false~~
* [x] return format 
  * [x] csv
  * [x] tsv

# Analysis

The `total(bool)` count will not be implemented as currently needs another query to count the results or obtain all the results in a single page and count the objects. As currently performance is first, this count might be implemented in a later issue but will be excluded of this one.

Refer to [issue #7 ](https://github.com/datopian/data-api/issues/7)

**Comment by leomrocha** [comment]
Closing the issue as all the things that will be implemented are already in place.
As per the updated analysis section count will not be currently implemented.
