### ISSUE TITLE
CSV response format for graphql read API

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-api#5]
When I have selected the data I want in the Build Report I want to be able to download in CSV format so that I can use it easily in my tools e.g. a spreadsheet, database etc

## Acceptance

* [x] I can make a query to build report API and indicate that I want results returned in CSV
* [x] The results are returned in CSV

## Tasks

* [x] Design the API structure
* [x] Add format query string to "graphql" endpoint with default to JSON
* [x] Stream response instead of simple response.
* [x] Implement CSV format option with conversion to CSV from JSON response
  * [x] Implement different separation formats TSV, `|`, `;`, 
  * [x] Tests

### Current
```
/.../graphql
```

POST request

```
{  query MyQuery {
    build_report_capacityauction {
      MonthlyAuctionConRentDKK_DK1
      UtilizedExportCapacity_DK1
    }
  }
}
```

### New

POST with existing type of body to:

```
.../graphql?format=json|csv|xlsx
```

### Options

New format:

Option 1:

POST /.../

Nicest:

.../graphql?format=json|csv|xlsx

Option 2:

```
{
  "format": "json | csv | xlsx",
  "graphql": "query MyQuery {
    build_report_capacityauction {
      MonthlyAuctionConRentDKK_DK1
      UtilizedExportCapacity_DK1
    }
  }"
}
```

**Comment by leomrocha** [comment]
All formats supported by (js-xlsx)[https://github.com/SheetJS/sheetjs] will be easy to support with data-api after the current branch is tested and merged to the master.
For accepted formats read [Library Documentation](https://docs.sheetjs.com/)

**Comment by rufuspollock** [comment]
@leomrocha  👏 👏 

Can we add a comment when closing as per https://playbook.datopian.com/issues-tasks/#closing-issues

**Comment by leomrocha** [comment]
Functionality implemented and tested in the Merged code feature/downloads PR #20
