### ISSUE TITLE
XLSX response format for read API 

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-api#6]
When I have selected the data I want in the Build Report I want to be able to download in XLSX format so that I can use it easily in my tools e.g. Excel

## Acceptance

* [x] I can make a query to build report API and indicate that I want results returned in xlsx (or excel?)
* [x] The results are returned in xlxs format

## Tasks

* [x] Design the API structure - same as for CSV #5
* [x] Implement xlsx format option with conversion to xlsx from JSON response
  * [x] Basic test

## Analysis:

See [CSV related issue](https://github.com/datopian/data-api/issues/5#issue-695876989)

**Comment by leomrocha** [comment]
Functionality implemented and tested in the Merged code feature/downloads PR #20
